services:
  kratos-selfservice-ui:
    image: ghcr.io/bearded-impala/kratos-selfservice-ui-react-fastapi:latest
    pull_policy: always
    ports: ["4455:4455"]
    environment:
      KRATOS_PUBLIC_URL: http://host.docker.internal:4433
      ORY_CONFIG: |
        {
          "project": {
            "name":"Company",
            "logo_light_url":"https://www.svgrepo.com/download/330413/fastapi.svg"
          },
          "intl":{"locale":"en"}
        }
