services:
  kratos-selfservice-ui:
    image: kratos-selfservice-ui:dev
    build: .
    ports: ["4455:4455"]
    environment:
      KRATOS_PUBLIC_URL: http://host.docker.internal:4433
      KRATOS_UI_BASE_PATH: /
      ORY_CONFIG: |
        {
          "project": {
            "name": "Company",
            "default_locale": "en",
            "logo_light_url": "https://www.svgrepo.com/download/330413/fastapi.svg",
            "favicon_light_url": "https://www.svgrepo.com/download/330413/fastapi.svg",
            "registration_enabled": true,
            "recovery_enabled": true,
            "verification_enabled": true
          },
          "intl": {
            "locale": "en"
          }
        }
